### PR TITLE
Update compatibility matrix

### PR DESCRIPTION
**Pull request by segfaultxavi**

### CODE REVIEW

**Comment by fboucquez** [comment]
Both SDKs will be `v0.21.0`

Is it possible to add symbol-bootstrap to the matrix?

- v0.0.0 is be 0.9.6.4 compatible.
-  v0.1.0 would be 0.9.7.? compatible.

Now users would now which version of bootstrap to install and use when running a particular version of the network. 

Something like:

````
*****
APIs
*****

.. csv-table::
    :header: "Milestone", "OpenAPI", "Rest", "SDK TS", "SDK Java", "Bootstrap"
    :delim: ;

    `v0.9.7.0 <https://github.com/nemtech/catapult-server/blob/main/CHANGELOG.md#0970---15-sep-2020>`_; v0.9.7; v2.0.0; v0.21.0; v0.21.0; v0.1.0
    `v0.9.6.4 <https://github.com/nemtech/catapult-server/blob/main/CHANGELOG.md#0964---27-jul-2020>`_; v0.9.6; v1.2.1; v0.20.7; v0.20.3; v0.0.0
    `v0.9.6.3 <https://github.com/nemtech/catapult-server/blob/main/CHANGELOG.md#0963---10-jul-2020>`_; v0.9.4; v1.1.3; v0.20.6; v0.20.2;
    `v0.9.5.1 <https://github.com/nemtech/catapult-server/blob/main/CHANGELOG.md#0951---22-may-2020>`_; v0.8.11; v1.0.20.50; v0.19.2; v0.19.0;
    `v0.9.4.1 <https://github.com/nemtech/catapult-server/blob/main/CHANGELOG.md#0941---23-april-2020>`_; v0.8.11; v1.0.20.31; v0.18.0; v0.17.2;

- `OpenAPI CHANGELOG <https://github.com/nemtech/symbol-openapi/blob/main/CHANGELOG.md>`_
- `REST CHANGELOG <https://github.com/nemtech/catapult-rest/blob/main/CHANGELOG.md>`_
- `SDK TS CHANGELOG <https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/main/CHANGELOG.md>`_
- `SDK Java CHANGELOG <https://github.com/nemtech/symbol-sdk-java/blob/main/CHANGELOG.md>`_
- `Symbol Bootstrap CHANGELOG <https://github.com/nemtech/symbol-bootstrap/blob/main/CHANGELOG.md>`_

````

If this table gets too big, maybe split it between Server and API?

**Comment by segfaultxavi** [comment]
> Both SDKs will be `v0.21.0`

Added. Thanks.

> Is it possible to add symbol-bootstrap to the matrix?

I think it makes sense. Done.

> If this table gets too big, maybe split it between Server and API?

Right now I think it is still manageable. We can always split it in the future, for sure.

**Comment by Vektrat** [comment]
> > Both SDKs will be `v0.21.0`
> 
> Added. Thanks.
> 
> > Is it possible to add symbol-bootstrap to the matrix?
> 
> I think it makes sense. Done.
> 
> > If this table gets too big, maybe split it between Server and API?
> 
> Right now I think it is still manageable. We can always split it in the future, for sure.

honestly i think it does not make sense to add the bootstrap to the matrix, it is a tool unrelated to the API and clients, i think bootstrap should just define what clients it is using, or what Milestone if we decide to use bootstrap like so

i also think it doesn't make sense to split the table between server and API (assuming you mean catapult REST, because core isn't listed atm), because OpenApi is basically a representation of REST and they go hand by hand. Also, right now we just have two major SDKs (TS and Java), but this may not be the case in the near future and i don't think this table is the place for listing the SDKs, instead, each SDK should list its own compatibility matrices in their project

supporting both opinions i add the example of the relationship of REST and catapult-server, REST has its own compatibility docs regarding the server in its own repo, and the server is not displayed here, nor REST is displayed in the `catapult-server` project

**Comment by Vektrat** [comment]
just checked the docs again, if the SDKs grew we could list them under a new section `SDKs` (or subsection `SDKs` within the APIs section)s

in the same manner, bootstrap could be placed in its own section

**Comment by segfaultxavi** [comment]
I thought adding Bootstrap to the matrix made sense because it is sort of mandatory to use it? Or am I mistaken?

The "Wallets" section could be renamed "Tools", and contain "Desktop Wallet", "CLI Wallet", "Bootstrap" and others.
An "SDKs" section will make sense once we have more of them, for sure.

**Comment by Vektrat** [comment]
> I thought adding Bootstrap to the matrix made sense because it is sort of mandatory to use it? Or am I mistaken?
> 
> The "Wallets" section could be renamed "Tools", and contain "Desktop Wallet", "CLI Wallet", "Bootstrap" and others.
> An "SDKs" section will make sense once we have more of them, for sure.

it's not mandatory, it is a quality of life tool and i believe at the moment anyone who wants to make a serious deploy will probably get in depth and deploy the projects individually for more control and understanding - though since right now most of the deploys are probably experimental and dev focused it is extremely useful

**Comment by fboucquez** [comment]
The way I see it:

- Server: Server - Rest - Open Api - Bootstrap 
- SDKs: Typescript - Java - (more languages in the future)
- Clients: CLI, Wallet,  Faucet, Explorer, etc

**Comment by fboucquez** [comment]
Nothing is really mandatory.  Somebody can just use an app like CLI or Wallet and connect to Testnet. Bootstrap is a nice tool to run your own networks and/or nodes. 
I think it makes sense to be in the general matrix. If you want to run server/rest version X/Y, use/install bootstrap Z.

Before, you need to clone and checkout a specific tag/commit (in some fork) in to run a particular version in of catapult-service-bootstrap or symbol-testnet-bootstrap. Now releases and versioning align with the other artifacts.

**Comment by segfaultxavi** [comment]
Let's land this **without** adding Symbol Bootstrap and then we continue discussing where exactly in the page should we add its version history someplace else. Maybe in #514.

**Review by rg911 — APPROVED** [review]

**Pull request merged**
