### PR TITLE
Added finalized block ws channel description

### PR DESCRIPTION
**Pull request by Vektrat**
blocked by:
- https://github.com/nemtech/catapult-rest/pull/462
- https://github.com/nemtech/symbol-openapi/pull/196

### CODE REVIEW

**Comment by segfaultxavi** [comment]
The link to the FinalizedBlockDTO gives me a 404 in the netlify preview. `FinalizedBlockDTO.yml` does not exist in the repo and it does not seem to be added by this commit.
What am I missing?

**Review by segfaultxavi — CHANGES_REQUESTED** [review]
The link to the FinalizedBlockDTO gives me a 404 in the netlify preview. `FinalizedBlockDTO.yml` does not exist in the repo and it does not seem to be added by this commit.
What am I missing?

**Comment by dgarcia360** [comment]
@segfaultxavi [nemtech/symbol-openapi#196](https://github.com/nemtech/catapult-rest/pull/462) adds the missing file. Once this issue is merged, it will be possible to accept this one - that's why @Vektrat added the ``blocked`` tag.

**Review by segfaultxavi — COMMENTED** [review]
OK, understood. Thanks, and sorry about the noise :)

**Comment by fboucquez** [comment]
The finalizedBlock payload has been merged into open API. This task should not be blocked anymore.

We have introduced a change to all the listener payloads (the only exception is the "uid" start one). They have been wrapped with a topic/data object:

```
{
"topic": "uri"
"data": {} | string (the old payload)
}
```

Examples:

```
{
  "data" : {
    "block" : {
      "beneficiaryAddress" : "989998EEA3CCAB841BDB2E640F6D67F722F8C641FB926A94",
      .....
      "version" : 1
    },
    "meta" : {
      "generationHash" : "5E4CC397392206A36CFAEA365E39D1011E6F1D7DC7E210DE6960ED41799EC452",
      "hash" : "5379554EC0C176EB3AF7C059254E77EC9C954ED938E07221540B51B3C7EEF20E"
    }
  },
  "topic" : "block"
}
```

````
{
  "data" : {
    "meta" : {
      .....
    },
    "transaction" : {
      ....
      "type" : 16724,
      "version" : 1
    }
  },
  "topic" : "confirmedAdded/TBTFPZEARRFILORDQTHSBFR3F6SIA77WAOL3LZA"
}

````

We should mention this change to all WS channel descriptions. Unsure if it is this task/pr or in another one. @segfaultxavi

**Comment by Vektrat** [comment]
this is still blocked, we just merged info relating to the endpoint, we still need to see what do we do with the WS DTO

**Comment by segfaultxavi** [comment]
Meanwhile, I'll create a separate issue for the payload format changes.

**Comment by fboucquez** [comment]
WS issue https://github.com/nemtech/symbol-docs/issues/504

**Comment by Vektrat** [comment]
> Meanwhile, I'll create a separate issue for the payload format changes.

btw this task (the new one) should be considered of high priority since it's already in and it affects the whole ws environment ^^

**Comment by Vektrat** [comment]
not blocked anymore, we will reuse the DTO if you want because i made them to be of equal schema, though the original payload schema is different and might change in the future depending on whether core makes them more consistent or not

**Review by segfaultxavi — APPROVED** [review]
Let's land this. The commit makes sense, it is small enough and it matches the current descriptions of the other channels.
The payload format update comes next.

**Pull request merged**
